[workspace]
resolver = "2"

members = ["crates/*"]

[profile.debugging]
inherits = "dev"
opt-level = 0
debug = true

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

#[patch.crates-io]
#winit = { git = "https://github.com/rust-windowing/winit" }
